export interface Route {
  route_name: string;
  grade_YDS?: string;
  grade_French?: string;
  grade_Ewbanks?: string;
  grade_UIAA?: string;
  grade_ZA?: string;
  grade_British?: string;
  safety: string;
  type_trad?: boolean;
  type_tr?: boolean;
  type_sport?: boolean;
  type_aid?: boolean;
  type_ice?: boolean;
  type_boulder?: boolean;
  type_mixed?: boolean;
  type_snow?: boolean;
  type_alpine?: boolean;
  fa: string;
  description: string;
  location: string;
  protection: string;
  metadata_left_right_seq: string;
  metadata_parent_lnglat_0: number;
  metadata_parent_lnglat_1: number;
  metadata_parent_sector: string;
  metadata_mp_route_id: string;
  metadata_mp_sector_id: string;
}
